import { defineConfig, globalIgnores } from 'eslint/config';
import expoConfig from 'eslint-config-expo/flat.js';

import {
  complexityBudgetRules,
  errorTierRules,
  sharedIgnores,
  testFileRules,
  typeAwareErrorRules,
} from '../eslint.base.mjs';

// Expo app. `eslint-config-expo` is the Expo SDK 57 baseline and is taken whole:
// it already registers the TypeScript parser/plugin, React, react-hooks, import
// and the React Native globals. The blocks after it only re-tune severities to
// the project taste. Later blocks win, so order matters.
export default defineConfig([
  expoConfig,

  // Error tier: things that are always a bug.
  {
    files: ['src/**/*.{ts,tsx}'],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      ...errorTierRules,
      ...typeAwareErrorRules,
      // A hook called conditionally is a guaranteed runtime bug, not a style nit.
      'react-hooks/rules-of-hooks': 'error',
    },
  },

  // Warn tier: refactoring pressure on production source only.
  {
    files: ['src/**/*.{ts,tsx}'],
    rules: {
      ...complexityBudgetRules,
      // Exhaustive deps has a real false-positive rate; it nudges, never blocks.
      'react-hooks/exhaustive-deps': 'warn',
      // New in eslint-plugin-react-hooks 7 and currently violated by the canonical
      // React Native `useRef(new Animated.Value(x)).current` idiom in the skeleton
      // components. Stays a warning until that count reaches zero; promote then.
      'react-hooks/refs': 'warn',
    },
  },

  // Test files: same error tier, relaxed size budget.
  {
    files: ['**/__tests__/**/*.{ts,tsx}', '**/*.test.{ts,tsx}'],
    rules: testFileRules,
  },

  globalIgnores([
    ...sharedIgnores,
    '.expo/**', // Expo dev/build intermediates, regenerated on every start
    'expo-env.d.ts', // generated by the Expo CLI
  ]),
]);
